name: ir_sensor_plugin
description: This plugin allows Flutter applications to use the infrared sensor on Android starting with API 19
version: 0.3.1
homepage: https://github.com/Yeikel200/ir_sensor_plugin

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ir_sensor_plugin
        pluginClass: IrSensorPlugin